on:
  push:
    branches:
    - main
jobs: 
  autoDoc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: mkdir -p path/to/artifact

    - run: echo hello > path/to/artifact/world.txt

    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: path/to/artifact/world.txt
        
    #- run: ls -a ${workspace} #jsdoc espose.js 
        
     # - name: moveDocFile
      #  run: cp out/* ~/work/testElectronApp/documentation/ 
    #- name: installJSdocs
    # - name: docFiles
      #  run: npm install -g jsdoc
