on:
  push:
    branches:
    - main
jobs: 
  autoDoc:
    runs-on: ubuntu-latest
    steps:
      - name: installJSdocs
        run: npm install -g jsdoc
        
      - name: docFiles
        run: jsdoc espose.js
        
      - name: moveDocFile
        run: cp out/* ~/testElectronApp/documentation/ 
    
