# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Install eslint
        run: npm install -g eslint
      - name: Install yarn
        run: yarn 
      - name: Run ESLint config
        run: npm init @eslint/config -- --config semistandard,standard
      - name: Run ESLint
        run: eslint . --ext .js,.jsx,.ts,.tsx
        
