on:
  push:
    paths:
    - '**.js'
    branches:
    - main
    
jobs: 
  myJob:
    runs-on: ubuntu-latest
    steps:
    -  name: installJSdocs
    -  run: npm install -g jsdoc
    
    -  name: docFiles
    -  run: jsdoc **.js
    
    -  name: pdocFiles
    -  run: echo ~/.bash_history
    
    
      
 

        
    #- run: ls -a ${workspace} #jsdoc espose.js 
        
     # - name: moveDocFile
      #  run: cp out/* ~/work/testElectronApp/documentation/ 
    #- name: installJSdocs

