name: GitHub pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./
          output_dir: ./out
          template: minami
          front_page: README.md

      - name: Print
        run: ls -la /home/runner/work/testElectronApp/testElectronApp/
     # - name: Deploy
     #   uses: peaceiris/actions-gh-pages@v3
     #   with:
      #   deploy_key: ${{ secrets.GITHUB_TOKEN  }}
       #  publish_dir: ./home/runner/work/testElectronApp/testElectronApp/out


      #-  name: docFiles
      #   run: jsdoc **.js

      #-  name: pdocFiles
      #   run: echo ~/.bash_history
         
         
         
    
    
      
 

        
    #- run: ls -a ${workspace} #jsdoc espose.js 
        
     # - name: moveDocFile
      #  run: cp out/* ~/work/testElectronApp/documentation/ 
    #- name: installJSdocs

